version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: sitio_web
    volumes:
    - ./BASICA:/var/www/html/
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "80:80"
